"""Final deterministic gate for Gurobean Engine v2_6 live-game testing.

This command never fabricates a Gurobi or real-game PASS. It consumes the
post-patch R9 release artifact generated by scripts/r9_release.py and checks
that it belongs to the current Git HEAD. R5-R8 remain explicitly
calibration/evidence-gated; that is compatible with being ready to run a live
game test, but not with claiming formal game parity.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARTIFACT = ROOT / "r9_release_certification.json"


def git_head() -> str:
    return subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=ROOT, text=True
    ).strip()


def source_dirty() -> list[str]:
    output = subprocess.check_output(
        ["git", "status", "--porcelain"], cwd=ROOT, text=True
    )
    # The R9 artifact is a generated certification output and is intentionally
    # not committed because committing it would change HEAD and invalidate the
    # exact-commit attestation it contains.
    return [
        line for line in output.splitlines()
        if line.strip() and not line.endswith("r9_release_certification.json")
    ]


def main() -> int:
    print("=== GUROBEAN ENGINE v2_6 — FINAL LIVE-TEST GATE ===")
    head = git_head()
    print(f"GIT_HEAD: {head}")

    if not ARTIFACT.is_file():
        print("R9_ARTIFACT: MISSING")
        print("STATUS: NOT_READY")
        print("BLOCKER: run scripts/check_gurobi.py and scripts/r9_release.py on this exact clean commit")
        return 2

    try:
        artifact = json.loads(ARTIFACT.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        print(f"R9_ARTIFACT: INVALID ({type(exc).__name__})")
        print("STATUS: NOT_READY")
        return 2

    exact = artifact.get("git_commit") == head
    r9_pass = (
        artifact.get("status") == "PASS"
        and artifact.get("gurobi_gate") == "CHECKED"
        and artifact.get("cases_checked") == 400
        and artifact.get("failures") == 0
        and exact
    )
    dirty = source_dirty()
    clean_enough = not dirty

    print(f"R9_STATUS: {artifact.get('status')}")
    print(f"GUROBI_GATE: {artifact.get('gurobi_gate')}")
    print(f"CASES_CHECKED: {artifact.get('cases_checked')}")
    print(f"FAILURES: {artifact.get('failures')}")
    print(f"EXACT_COMMIT_MATCH: {'PASS' if exact else 'FAIL'}")
    print(f"SOURCE_TREE_CLEAN: {'PASS' if clean_enough else 'FAIL'}")
    print("R5_R8: CALIBRATION_GATED")

    approved = r9_pass and clean_enough
    if approved:
        print("STATUS: GUROBEAN ENGINE v2_6 — APROBADO PARA PRUEBA CON JUEGO EN VIVO")
        print("NOTE: R5-R8 are not being promoted to formal game-parity certification.")
        return 0

    print("STATUS: NOT_READY")
    if not exact:
        print("BLOCKER: R9 artifact does not match current HEAD; rerun the release gate.")
    if not clean_enough:
        print("BLOCKER: source files changed after certification:")
        for entry in dirty:
            print(f"  {entry}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
